import type { NativeStackNavigationProp } from '@react-navigation/native-stack';
import type { Order } from '../services/orders/orderService';

/**
 * Type definitions
 */
export interface User {
  id: string;
  name: string;
  email: string;
  avatar?: string;
}

import type { RouteProp } from '@react-navigation/native';

export interface NavigationProps<T extends keyof RootStackParamList = keyof RootStackParamList> {
  navigation?: NativeStackNavigationProp<RootStackParamList, T>;
  route?: RouteProp<RootStackParamList, T>;
}

// Main Tab Navigator - Bottom tab navigation
export type MainTabParamList = {
  Home: undefined;
  Categories: undefined;
  Cart: { appliedCoupon?: { code: string; discount: number } } | undefined;
};

// Root Stack - Main navigation from Settings
export type RootStackParamList = {
  Splash: { next?: 'Login' } | undefined;
  Onboarding: undefined;
  NoInternet: undefined;
  Login: { fromSplash?: string } | undefined;
  OTPVerification: { phoneNumber: string; sessionId?: string };
  VerificationSuccess: { autoGeneratedPassword?: string; isNewUser?: boolean } | undefined;
  LocationPermission: { fromAuth?: boolean } | undefined;
  MainTabs: {
    screen?: 'Home' | 'Categories' | 'Cart';
    params?: {
      appliedCoupon?: { code: string; discount: number };
    };
  } | undefined;
  OrderStatus: undefined;
  Settings: undefined;
  Orders: undefined;
  CustomerSupport: { orderId?: string } | undefined;
  Addresses: undefined;
  Refunds: undefined;
  Profile: undefined;
  PaymentManagement: undefined;
  GeneralInfo: {
    screen?: 'GeneralInfo' | 'TermsAndConditions' | 'PrivacyPolicy';
  } | undefined;
  Notifications: undefined;
  Checkout: { appliedCoupon?: { code: string; discount: number } } | undefined;
  Payment: {
    totalBill?: number;
    itemCount?: number;
    deliveryTip?: number;
    appliedCoupon?: { code: string; discount: number };
    addressId?: string;
    /** Standalone `/api/payment/initiate` → SDK (or simulate) → `/api/payment/callback` flow */
    standaloneSession?: {
      sessionPayload: unknown;
      orderId: string;
      clientOrderRef: string;
      txnId: string;
      amount: number;
      /** From POST /api/payment/initiate — aligns SDK `deviceId` with server token (`sh1`|`sh2`). */
      hashAlgo?: string;
    };
  } | undefined;
  PaymentSuccess: { orderId: string };
  Coupons: undefined;
  Home: undefined;
  Category: undefined;
  Search: undefined;
  SearchResults: { query: string };
  ProductDetail: { productId: string };
  CategoryProducts: { categoryId: string; categoryName: string };
  CollectionProducts: { collectionId: string };
  DynamicPage: { slug: string };
  BannerDetail: { title?: string; bannerId?: string; contentItemId?: string };
  TinyTimmies: undefined;
  CategoriesExpo: undefined;
  Cart: { appliedCoupon?: { code: string; discount: number } } | undefined;
  Wallet: undefined;
  AdminCms: undefined;
};

// Refunds Stack - Nested navigation for refunds
export type RefundsStackParamList = {
  Refunds: undefined;
  RefundDetails: { refundId: string; orderNumber?: string };
  ReturnRequest: { orderId?: string };
};

// Orders Stack - Nested navigation for orders flow
export type OrdersStackParamList = {
  MyOrders: undefined;
  OrderCanceledDetails: { orderId?: string };
  OrderSuccessfulDetails: { orderId?: string };
  RateOrder: { orderId?: string };
  RatingSuccess: undefined;
  OrderStatusMain: undefined;
  OrderReceived: { orderId?: string };
  OrderStatusDetails: { orderId?: string; status: 'getting-packed' | 'on-the-way' | 'arrived' };
  OrderItemsDetails: {
    orderId?: string;
    orderNumber?: string;
    items?: Array<{
      id: string;
      name: string;
      weight: string;
      quantity: number;
      discountedPrice: number;
      originalPrice: number;
      image?: string;
      itemStatus?: string;
    }>;
    status?: 'getting-packed' | 'on-the-way' | 'arrived';
    deliveryAddress?: string;
    totalSavings?: number;
    itemTotal?: number;
    handlingCharge?: number;
    deliveryFee?: number;
    totalBill?: number;
    createdAt?: string;
  };
  OrderChat: { orderId: string; orderNumber?: string };
};

// Location Stack - Nested navigation for address flow
export type LocationStackParamList = {
  SavedAddressesEmpty: undefined;
  SavedAddressesList: undefined;
  LocationSearch: undefined;
  LocationSearchResults: { searchQuery?: string };
  MapAddressPin: {
    location?: {
      title: string;
      address: string;
      latitude?: number;
      longitude?: number;
      city?: string;
      useGPS?: boolean;
    };
  };
  EnterCompleteAddress: {
    location?: {
      title: string;
      address: string;
      city?: string;
      state?: string;
      pincode?: string;
      area?: string;
      latitude?: number;
      longitude?: number;
    };
    editAddressId?: string;
    editData?: {
      houseNo: string;
      building: string;
      landmark: string;
      label: string;
      city: string;
      state: string;
      pincode: string;
    };
  };
  AddressSavedSuccess: undefined;
};

// General Info Stack - Nested navigation for general info
export type GeneralInfoStackParamList = {
  GeneralInfo: undefined;
  TermsAndConditions: undefined;
  PrivacyPolicy: undefined;
};

// Customer Support Stack - Nested navigation for help & support
export type CustomerSupportStackParamList = {
  CustomerSupport: undefined;
  HelpSubSection: { sectionName: string };
  ContactSupport: undefined;
  GeneralChat: undefined;
};

// Navigation prop types
// RouteProp is imported above with NavigationProps

export type RootStackNavigationProp = NativeStackNavigationProp<RootStackParamList>;
export type RootStackRouteProp<T extends keyof RootStackParamList> = RouteProp<RootStackParamList, T>;
export type OrdersStackNavigationProp = NativeStackNavigationProp<OrdersStackParamList>;
export type OrdersStackRouteProp<T extends keyof OrdersStackParamList> = RouteProp<OrdersStackParamList, T>;
export type LocationStackNavigationProp = NativeStackNavigationProp<LocationStackParamList>;
export type GeneralInfoStackNavigationProp = NativeStackNavigationProp<GeneralInfoStackParamList>;
export type CustomerSupportStackNavigationProp = NativeStackNavigationProp<CustomerSupportStackParamList>;
export type RefundsStackNavigationProp = NativeStackNavigationProp<RefundsStackParamList>;

